# These are supported funding model platforms

github: turkerpw
patreon: turkerpw
open_collective: turkerpw
ko_fi: turkerpw
tidelift: turkerpw
community_bridge: turkerpw
liberapay: turkerpw
issuehunt: turkerpw
otechie: turkerpw
lfx_crowdfunding: turkerpw
custom: turkerpw
